[package]
name = "graph"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
egui = "0.33.0"
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug" }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug" }
